### ISSUE TITLE
Applying Loop doesn't loop synchronously 

### ISSUE THREAD

**Issue by jonleecraw** [CoderLine/alphaTab#192]
# Your environment

Version used: (master branch)
Platform used: JavaScript
Rendering engine used: both SVG and HTML5
Browser Name and Version: both Chrome 68.0.3440.84 and FireFox 61.0.1
Operating System and version (desktop or mobile): Windows 10 Desktop (i7 6700k, 1070 gpu, 16gb RAM)

# Expected Results
When setting loop as true through the API, it is expected that it will loop without a noticeable interruption to the playback. This should be true both in just setting an entire opened document (GP5 file in this case) to loop, as well as setting a playback range to loop.

# Observed Results
There is a noticeable delay between when playback starts and reaches the end of the playback range, and when the playback starts again (creating a loop). There is also some sound artifacts that occur (the last note in the loop carries into the beginning of the next loop playback for a short duration). This artifact sometimes appears just by playing a document, hitting stop or letting it finish playback, and hitting play again. 

# Steps to Reproduce (for bugs)
 
1.  Open a GP5 file in a rendered webpage.
2. Set the playback to loop (in the page or with the developer console of your browser):

```
at.alphaTab('loop', true);
/* optionally, set a playback range */
var range = {};
range.StartTick = 0;
range.EndTick = (960 * 4);
at.alphaTab('playbackRange', range);
/* end option */
```

3.  Trigger a play command (through rendered controls or the API):

```
at.alphaTab('playPause');
```

# Possible Solution 
It's possible the playback sound buffers could be cleared before looping to prevent the artifact that occurs on loop. 

As for flawless (or closer to) looping, perhaps a second instance of the playback engine can be loaded in anticipation for the loop, and alternate between the two. This sounds very heavy handed, but just a suggestion. Or perhaps the playback engine can anticipate when it is near the end of a playback in a loop, and lazy-load the beginning of the playback range on the end of the current playback. Then continue with this method, and void/garbage cleanup the beginning of the playback data, like a stack: you keep adding new measures of playback to top, and removing old playback measures from the bottom.

I don't understand the engine at all, so these suggestions might be completely useless.

**Comment by Danielku15** [comment]
The problem is already fixed on the develop branch. Please try the version from there. 

The reason was mainly a buffer inside the ScriptProcessorNode which got played when connected to the output. Now the Node is recreated on play/pause.

**Comment by jonleecraw** [comment]
This issue still persists for me; Trying on both up to date Chrome and Firefox on Windows 10 and using the dev branch release from 4-13-19. I'm not sure what I'm doing wrong, but there is still a very jarring sequence break at the loop point, making it impossible to loop over a few measures for the purpose of instrument practice exercises.

**Comment by vsqla** [comment]
Its still here+
