### ISSUE TITLE
Master Volume not working

### ISSUE THREAD

**Issue by MDoder97** [CoderLine/alphaTab#399]
# Your environment

VSCode

* Version used: (master branch)
* Platform used: JavaScript
* Browser Name and Version: Chrome
* Operating System and version Desktop

# Expected Results
Connected master volume to the slider, it didn't work however. I then tried to just call api.masterVolume = 0 right after api initialization, still nothing.

i'm including script from cdn - https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/alphaTab.js

Code i used

    const settings = {
      file: 'https://www.alphatab.net/files/canon.gp',
      player: {
        enablePlayer: true,
        soundFont:
          'https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/soundfont/sonivox.sf2',
      },
    };
    const api = new alphaTab.AlphaTabApi(tab, settings);
    api.masterVolume = 0;

**Comment by cheap-glitch** [comment]
You need to call `updateSettings` to apply the changes:
https://www.alphatab.net/docs/reference/api/updatesettings/

**Comment by MDoder97** [comment]
If you mean calling it right after i set masterVolume, still doesn't work, also with slider it causes significant lag as it gets updated often. PlaybackSpeed works just fine with slider right out of the gate though.

**Comment by Danielku15** [comment]
I can confirm that this is a bug. I just checked the sequence and there is a missing unit conversion missing for the master volume. I will try to provide a fixed version this evening.

**Comment by Danielku15** [comment]
I didn't manage to sit down yesterday to add the required change. So with 1 day delay the fix is available 😉

**Comment by MDoder97** [comment]
Thanks! Is it available with 1.1 release though or right now? I'm pulling the latest from cdn and it still doesn't work here. Sorry if i'm missing something, i'm new. :)

**Comment by Danielku15** [comment]
It is available via 1.1.0+alpha.42, either you use this version or the `alpha` tag for early access. 
 
https://www.npmjs.com/package/@coderline/alphatab
