### ISSUE TITLE
GPX issues

### ISSUE THREAD

**Issue by mbektimirov** [CoderLine/alphaTab#91]
Hi Daniel, I've found some critical gpx reading issues and listed it below. I will continue to add it in this thread if there will be some more bugs.

- Some strange render artifacts:
![image](https://cloud.githubusercontent.com/assets/918009/15429745/bb16a922-1ebb-11e6-8fea-b88cb9e750e0.png)
Tab: [lion_king-hakuna_matata_arr_by_fabio_lima.gpx.zip](https://github.com/CoderLine/alphaTab/files/274678/lion_king-hakuna_matata_arr_by_fabio_lima.gpx.zip)

- This tab is failing on whammy bar reading (easy fix) and drum track reading which is empty: 
[Metallica - For Whom The Bell Tolls.gpx.zip](https://github.com/CoderLine/alphaTab/files/274682/Metallica.-.For.Whom.The.Bell.Tolls.gpx.zip)

**Comment by Danielku15** [comment]
I fixed the 2 rendering issues you mentioned. the first was related to arpeggio rendering. I mixed the y coordinate with the scale which lead to this huge wave symbols being rendered :sweat_smile:  

The whammy reading was really easy to fix. There was a break missing. I'm not yet sure whar the WhammyBarExtend exactly means so I simply ignore it. 

Regarding the track rendering I just got a question regarding this via mail and fixed it already. The bug was related to some missing call to the accidental helper which does the actual note line calculation. 

Feel free to reopen the issue if you discover more issues.

**Comment by mbektimirov** [comment]
The problem is still the same with drum track and Metallica tab. It breaks on `StaveGroup.BuildBoundingsLookup` where `firstStaveInAccolade` is null when I'm trying to render the drums track.

**Comment by mbektimirov** [comment]
I think it is a gpx parser bug because drums are not playing at all in this tab.

**Comment by Danielku15** [comment]
The drum track renders fine on my machine but yes it's not playing. I'll check what happens there.

**Comment by Danielku15** [comment]
I added proper parsing of the element/variation tags that are used for drumkits on Guitar Pro 6. This way the drum tabs are properly rendered and played.

**Comment by mbektimirov** [comment]
Thanks, it works perfect!
